---
- name: Проверить, что список VLAN не пустой
  ansible.builtin.assert:
    that:
      - vlans | length > 0
    fail_msg: "Заполните vlans в vars/vlan_ensure.yml"

- name: Выполнить задачи VLAN для {{ ansible_network_os }}
  ansible.builtin.include_tasks: "{{ ansible_network_os }}.yml"
